### ISSUE TITLE
Error in loading state_dict for IClassifier

### ISSUE THREAD

**Issue by bryanwong17** [vkola-lab/tmi2022#1]
Hi, I faced this kind of problem when running build_graphs.py. Could you tell me what is the reason for this error? Is it because of inconsistency between out_dim in config.yaml and the number of classes defined in build_graphs.py?

Thank you in advance

RuntimeError: Error(s) in loading state_dict for IClassifier:
        size mismatch for fc.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([2, 512]).
        size mismatch for fc.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([2]).

**Comment by GSWS** [comment]
Hi bryanwong17,

The out_dim in config.yaml is the output dim for calculating contrastive loss, and we define the model as ResNetSimCLR [https://github.com/vkola-lab/GraphCAM/blob/f7709519adae594760456073d97166c3920cb5ad/feature_extractor/models/resnet_simclr.py#L6](url).

And when we load the feature extractor in build_graphs.py, we define the model as IClassifier: [https://github.com/vkola-lab/GraphCAM/blob/f7709519adae594760456073d97166c3920cb5ad/feature_extractor/cl.py#L14](url).

You have this error because the FC layers are different. You could ignore the fc layers since we use the hidden features from resnet trained with contrastive learning. To solve your issue, you could add a few lines below after [https://github.com/vkola-lab/GraphCAM/blob/f7709519adae594760456073d97166c3920cb5ad/feature_extractor/build_graphs.py#L161](url)
```ruby
try:
  state_dict_weights.pop('module.l1.weight')
  state_dict_weights.pop('module.l1.bias')
  state_dict_weights.pop('module.l2.weight')
  state_dict_weights.pop('module.l2.bias')
except:
  state_dict_weights.pop('l1.weight')
  state_dict_weights.pop('l1.bias')
  state_dict_weights.pop('l2.weight')
  state_dict_weights.pop('l2.bias')
```
to discard l1 and l2 when you load the trained feature extractor obtained from (b) Training Patch Feature Extractor.

**Comment by bryanwong17** [comment]
Hi GSWS,

Thank you very much for your help. I do have one question again in build_graphs.py 

bags_list = glob.glob(args.dataset)

args.dataset is the path to patches (in my case: "../../dataset/tiles/colon/combine") , right? When I tried to print out the len(bags_list), the program always give me output 1 and resulted in only one for loop in the compute_feats.

Could you please assist me in determining what's wrong?

Thank you very much!

**Comment by bryanwong17** [comment]
Hi GSWS,

Thank you very much for your help! I solved that problem. However, I met an issue when trying to run the code again:

Traceback (most recent call last):
  File "build_graphs.py", line 200, in <module>
    main()
  File "build_graphs.py", line 197, in main
    compute_feats(args, bags_list, i_classifier, args.output)
  File "build_graphs.py", line 118, in compute_feats
    feats, classes = i_classifier(patches)
  File "C:\Users\kirc\.conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\MedicalAI\Graph VIT for WSI Classification - Copy\feature_extractor\cl.py", line 25, in forward
    c = self.fc(feats.view(feats.shape[0], -1)) # N x C
  File "C:\Users\kirc\.conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\kirc\.conda\envs\torch\lib\site-packages\torch\nn\modules\linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\kirc\.conda\envs\torch\lib\site-packages\torch\nn\functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0

Could you help me to figure out what's the problem? Thank you very much for your kindness!

**Comment by bryanwong17** [comment]
Hi GSWS,

Thank you for your explanation! I solved that problem.

How should I adjust the function of save_coords and adj_matrix in build_graphs.py if one of my patch paths is like this: 2021S0388109010101-8 49.jpg (name of WSI-width position height position.jpg) so that it won't cause a problem for the following step?

Appreciate much for your help

**Comment by bryanwong17** [comment]
Hi GSWS,

Thank you for your explanation! I solved that problem.

In the save_coords function, are x and y represent the width and height of each patch? Do I need to store the name of WSI in c_idx.txt to differentiate patches from different WSI?

I also have this kind of error when running the code:

Traceback (most recent call last):
File "build_graphs.py", line 201, in
main()
File "build_graphs.py", line 198, in main
compute_feats(args, bags_list, i_classifier, args.output)
File "build_graphs.py", line 131, in compute_feats
adj_s = adj_matrix(csv_file_path, output)
File "build_graphs.py", line 62, in adj_matrix
adj_s = np.zeros((total, total))
numpy.core._exceptions.MemoryError: Unable to allocate 119. GiB for an array with shape (126264, 126264) and data type float64

Could you help me to figure out how to solve this issue? Thank you and appreciate much for your help!

**Comment by bryanwong17** [comment]
Hi GSWS,

Thank you for your explanation! That issue was already resolved.

Could you explain how to define args.dataset in the build graphs.py file? since len(bags list) is always 1 when I check

Is it also true that bags_list contains the WSI list? Is the compute_feats function used to compute the features for patches for every WSI?

Thank you and appreciate much for your help!
