### ISSUE TITLE
data organization

### ISSUE THREAD

**Issue by nabilapuspit** [vkola-lab/tmi2022#10]
Hi, can you tell me how you organize the data for your training. I'm a bit confuse when its going to 

> --data_path "path_to_graph_data" \

in the `train.sh` is it just the graphs we created from the previous step, the patches or the whole images. as short as I understand it refers to the graphs we made before right? then how do you call it, because if I only specify it into 

>  --data_path "./graphs" \

 it's not working. can you tell me what specific data to input to that process? `adj_s.pt`, `c_idx.txt`, `features.pt` or the whole files? thank you

**Comment by GSWS** [comment]
It refers to the graph we created. You could organize the structure of data at the specified folder 'graphs':
```
graphs/
	├── sample 1
    		├── adj_s.pt
    		├── c_idx.txt
    		└── features.pt
	├── sample 2
    		├── adj_s.pt
    		├── c_idx.txt
    		└── features.pt
	├── sample 3
    		├── adj_s.pt
    		├── c_idx.txt
    		└── features.pt
         ...
```
