### ISSUE TITLE
dataset used in the paper

### ISSUE THREAD

**Issue by pxliang** [vkola-lab/tmi2022#14]
Can you give more details of the data you used in the paper? For example, for CPTAC which data samples are used? Thank you

**Comment by GSWS** [comment]
1. CPTAC:
data sources: [LUAD](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=33948253) [LUSC](https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=33948248)
sample list: data/cptac.txt

2. TCGA:
data sources: [link](https://portal.gdc.cancer.gov/)
sample list: data/tcga.txt
