### ISSUE TITLE
could you provide the pre-trained feature extractor? 

### ISSUE THREAD

**Issue by WenxiongLiao** [vkola-lab/tmi2022#15]

**Comment by WenxiongLiao** [comment]
could you provide the pre-trained feature extractor? My email is liaowenxiong@yeah.net . Thank you.

**Comment by GSWS** [comment]
The pre-trained models can be <a href="https://drive.google.com/file/d/1JHwLqxg0RTNjQZXHqcSYnmLWVXiErulJ/view?usp=drive_link">downloaded</a>.
