### ISSUE TITLE
Loss v/s Epoch Curve

### ISSUE THREAD

**Issue by rM-planet** [vkola-lab/tmi2022#16]
Could you please provide the loss v/s epoch curve for your feature extractor and the downstream transformer model?

**Comment by GSWS** [comment]
Thank you for your question! Unfortunately, I don’t currently have the loss vs. epoch curve for the feature extractor and downstream transformer model available.

If you encounter any issues or have specific questions regarding the training process, feel free to reopen this issue, and I’d be happy to discuss and assist further.
