### ISSUE TITLE
Need help to run the code

### ISSUE THREAD

**Issue by az-ad** [vkola-lab/tmi2022#17]
Can you tell me the steps or full guidelines please, how can I run the code in Google colab. Actually I am a newbie and I am getting error when ever running the main.py . Thanks in advance.

**Comment by Itamar-Dalal** [comment]
Open Google Colab: Go to [Google Colab](https://colab.research.google.com/) in your web browser.

Sign in: Sign in with your Google account if you aren't already logged in.

Create a New Notebook:

Click on "File" in the top left corner.
Select "New Notebook" to create a new Python notebook.
Upload your code:

Click on the "File" menu.
Select "Upload Notebook."
Upload your main.py file.
Install Required Libraries:

In a code cell, you can install any required libraries using pip, for example:
python
Copy code
!pip install library_name
Run the Code:

In the code cell, type and run:
python
Copy code
%run main.py
This will execute your main.py file in the Colab environment.
Troubleshoot Errors:

If you encounter errors, carefully read the error messages in the output cells. They will often give you clues about what's wrong.
Check if you have imported necessary libraries.
Make sure the file paths in your code are correct.
Fixing Code: If you encounter issues with the code itself, you can make necessary changes directly in the Colab notebook. Ensure that the code works as intended before proceeding.

Save Your Work:

Click on "File" and select "Save" to save your changes to the notebook.
Share and Collaborate: You can share the Colab notebook with others by clicking on the "Share" button in the top-right corner. This allows for collaborative editing and sharing your work.

**Comment by az-ad** [comment]
!python '/content/tmi2022/main.py' after running this I am getting the error
Traceback (most recent call last):
  File "/content/drive/MyDrive/thesis/tmi2022/main.py", line 31, in <module>
    if not os.path.isdir(model_path): os.mkdir(model_path)
  File "/usr/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
How can I solve this

**Comment by Itamar-Dalal** [comment]
To run your code in Google Colab and address the error you're encountering, follow these steps:

Open Google Colab:

Go to Google Colab in your web browser.
Sign in with your Google account if you aren't already logged in.
Create a New Notebook:

Click on "File" in the top left corner.
Select "New Notebook" to create a new Python notebook.
Upload your code:

Click on the "File" menu.
Select "Upload Notebook."
Upload your main.py file.
Install Required Libraries (if needed):

In a code cell, you can install any required libraries using pip, for example:
python
Copy code
!pip install library_name
Run the Code:

In a code cell, type and run:
python
Copy code
!python '/content/tmi2022/main.py'
This will execute your main.py file in the Colab environment.
Troubleshoot Errors:

If you encounter errors, carefully read the error messages in the output cells. They often provide clues about what's wrong.
Check if you have imported necessary libraries.
Ensure the file paths in your code are correct.
Fixing Code:

If you encounter issues with the code itself, make necessary changes directly in the Colab notebook.
Ensure that the code works as intended before proceeding.
Save Your Work:

Click on "File" and select "Save" to save your changes to the notebook.
Share and Collaborate:

You can share the Colab notebook with others by clicking on the "Share" button in the top-right corner. This allows for collaborative editing and sharing your work.
Regarding the specific error you mentioned:

lua
Copy code
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
It appears that there may be an issue with the model_path variable in your main.py file. Make sure that model_path is defined correctly and is not set to None. You might need to modify your code to ensure that model_path is a valid string path before using it in the os.mkdir function.

**Comment by GSWS** [comment]
Thanks for your interest, and it’s hard for me to outline all the steps.
