### ISSUE TITLE
Inquiry about args.dataset in build_graphs.py

### ISSUE THREAD

**Issue by bryanwong17** [vkola-lab/tmi2022#2]
Hi @vkola-lab,

Thank you for your explanation! The earlier issue was already solved.

Could you explain how to define args.dataset in the build graphs.py file? Is it linked to the path to patches as you mentioned in the build_graphs.py's parser?

If it's true, does bags_list contain the patches list? Is the compute_feats function used to compute the features for every patch (doesn't matter whether it comes from the same or different WSI)? So that it will store a c_idx.txt, features.pt, adj_s.pt for every patch?

Please correct me if I am wrong. Thank you very much!

**Comment by maxmal1** [comment]
Hi, do you have an answer to this?
