### ISSUE TITLE
Regarding the classification of data label categories in the CPTAC lung dataset

### ISSUE THREAD

**Issue by Wll-37** [vkola-lab/tmi2022#22]
On the official website of the CPTAC dataset, there are only LUAD and LSCC categories. By comparing the cptac. txt file in your code with the official classification, it was found that the cptac dataset used in your paper divides these two categories into three categories. Did you classify them yourself or not? If it was divided by oneself, what are the relevant criteria? Or was it provided by a third-party research institution?

**Comment by GSWS** [comment]
Hi, you can find the 'Normal' or 'Tumor' information in the 'Specimen Type' column within the LUAD or LUSC Data Table. This column is how we categorize the data into three distinct groups.
[LUAD wiki](https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=%2Fsystem%2Ffiles%2Fcollectionmetadata%2F202407%2Fcptac_metadata_07-09-2024.json&filterState=%5B%7B%22id%22%3A%22Tumor%22%2C%22title%22%3A%22Tumor%22%2C%22field%22%3A%22Tumor%22%2C%22operation%22%3A%22eq%22%2C%22values%22%3A%22LUAD%22%7D%5D)
