### ISSUE TITLE
Inquiry about Feature Extractor

### ISSUE THREAD

**Issue by ghost** [vkola-lab/tmi2022#4]
Hi @vkola-lab,

Also, in order to acquire the patch feature extractor, do I need to divide the patches into training, val, and testing? because I combined all of the patches to create a feature extractor, and I'm concerned that using test data for training was considered cheating.

Thank you in advance!

**Comment by kangyuxin1006** [comment]
Hi, @vkola-lab, could you provide the pre-trained Feature Extractor? my e-mail is 996472651@qq.com. Thank you.
