### ISSUE TITLE
Pre-trained Feature Extractor

### ISSUE THREAD

**Issue by kangyuxin1006** [vkola-lab/tmi2022#6]
Hi @vkola-lab, could you provide the pre-trained feature extractor? My email is 996472651@qq.com. Thank you.

**Comment by GSWS** [comment]
Thanks for your interest, please find the pre-trained model in feature_extractor/model.pth

**Comment by kangyuxin1006** [comment]
Thank you@vkola-lab, could you tell me which datasets utilized for training this model（feature_extractor/model.pth）？

**Comment by vkola-lab** [comment]
We used NLST. Please read the paper for more info.
